## APS 2 - Sistemas de equações (matrizes).

Considerar epsilon_s = 0,0001%.

Explicar como funcionam os comandos de inversão de matriz e multiplicação de matrizes usados pela linguagem de programação Python.

In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

%matplotlib inline

### Dedução dos sistemas de equações:

<img src='scan1.JPG'>

<img src='scan2.JPG'>

### Exercício 12.23 

In [57]:
matrix = np.array([    [1,-1,-1,0],
                       [-35,0,-5,200],
                       [0,-27,5,0]
                       ])

matrix = matrix.astype('float64')

### Utilizando a eliminação de Gauss ingênua:

In [58]:
temp = matrix[1][0]/matrix[0][0]
for i in range(4): 
    matrix[1][i] -= temp*matrix[0][i]

In [60]:
temp = matrix[2][1]/matrix[1][1]
for i in range(4): 
    matrix[2][i] -= temp*matrix[1][i]

In [61]:
print(matrix)

[[1.000 -1.000 -1.000 0.000]
 [0.000 -35.000 -40.000 200.000]
 [0.000 0.000 35.857 -154.286]]


### i3:

In [62]:
i3 = -154.286/35.857
print(i3)

-4.302813955434085


### i2:

In [63]:
i2 = (40*i3+200)/-35
print(i2)

-0.7967840509324738


### i1:

In [64]:
i1 = i2+i3
print(i1)

-5.099598006366559


### O sinal negativo da corrente indica que ela tem sinal contrário ao que está no desenho acima.

### Exercício 12.25
utilizar eliminação de Gauss com pivotamento.

### Exercício 12.27

### Utilizando eliminação de Gauss com pivotamento (mesmo código usado acima, com pivotamento executado manualmente), vem:

In [87]:
matrix = np.array([   
    [1,-1,0,0,0,1,0],
    [0,1,-1,1,0,0,0],
    [-20,-10,-5,0,0,0,30],
    [0,0,1,-1,-1,0,0],
    [1,0,0,0,-1,1,0],
    [-20,0,0,0,0,25,-50]                   
                       ])

matrix = matrix.astype('float64')

Primeiro coeficiente:

In [88]:
temp = matrix[2][0]/matrix[0][0]
for i in range(7): 
    matrix[2][i] -= temp*matrix[0][i]

temp = matrix[4][0]/matrix[0][0]
for i in range(7): 
    matrix[4][i] -= temp*matrix[0][i]

temp = matrix[5][0]/matrix[0][0]
for i in range(7): 
    matrix[5][i] -= temp*matrix[0][i]

In [ ]:
print(matrix)

Segundo coeficiente:

In [89]:
temp = matrix[2][1]/matrix[1][1]
for i in range(7): 
    matrix[2][i] -= temp*matrix[1][i]

temp = matrix[4][1]/matrix[1][1]
for i in range(7): 
    matrix[4][i] -= temp*matrix[1][i]

temp = matrix[5][1]/matrix[1][1]
for i in range(7): 
    matrix[5][i] -= temp*matrix[1][i]

In [ ]:
print(matrix)

Terceiro coeficiente:

In [90]:
temp = matrix[3][2]/matrix[2][2]
for i in range(7): 
    matrix[3][i] -= temp*matrix[2][i]

temp = matrix[4][2]/matrix[2][2]
for i in range(7): 
    matrix[4][i] -= temp*matrix[2][i]

temp = matrix[5][2]/matrix[2][2]
for i in range(7): 
    matrix[5][i] -= temp*matrix[2][i]

In [ ]:
print(matrix)

Quarto coeficiente:

In [ ]:
temp = matrix[3][2]/matrix[3][2]
for i in range(7): 
    matrix[3][i] -= temp*matrix[2][i]

temp = matrix[4][2]/matrix[3][2]
for i in range(7): 
    matrix[4][i] -= temp*matrix[2][i]

temp = matrix[5][2]/matrix[3][2]
for i in range(7): 
    matrix[5][i] -= temp*matrix[2][i]

In [92]:
print(matrix)

[[1.000 -1.000 0.000 0.000 0.000 1.000 0.000]
 [0.000 1.000 -1.000 1.000 0.000 0.000 0.000]
 [0.000 0.000 -35.000 30.000 0.000 20.000 30.000]
 [0.000 0.000 0.000 -0.143 -1.000 0.571 0.857]
 [0.000 0.000 0.000 -0.143 -1.000 0.571 0.857]
 [0.000 0.000 0.000 2.857 0.000 33.571 -67.143]]


### Exercício 12.28

In [ ]:
matrix = np.array([   
    [1,0,0,0,1,-1,0],
    [1,-1,0,1,0,0,0],
    [0,0,1,-1,1,0,0],
    [0,-1,1,0,0,1,0],
    [0,0,2,0,-4,0,-20],
    [-6,0,0,8,4,0,0]                   
                       ])

matrix = matrix.astype('float64')