## APS 2 - Sistemas de equações (matrizes).

Considerar epsilon_s = 0,0001%.

Explicar como funcionam os comandos de inversão de matriz e multiplicação de matrizes usados pela linguagem de programação Python.

In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

%matplotlib inline

### Exercício 12.23 

In [12]:
matrix = np.array([[1, -1,-1, 0, 0, 0, 0],
    
                   [10,-5,0,-25,0,0,200],
                   
                   [0, 5,-20, 0,-5,-2,0],
    
                   [0,-1, 0, 1, -1, 0, 0],
                   
                   [0, 0, 1, 0, 0,-1, 0],
                   
                   [0, 0, 0, 0, 1,-1, 0]])

matrix = matrix.astype('float64')
print(matrix)

[[1.000 -1.000 -1.000 0.000 0.000 0.000 0.000]
 [10.000 -5.000 0.000 -25.000 0.000 0.000 200.000]
 [0.000 5.000 -20.000 0.000 -5.000 -2.000 0.000]
 [0.000 -1.000 0.000 1.000 -1.000 0.000 0.000]
 [0.000 0.000 1.000 0.000 0.000 -1.000 0.000]
 [0.000 0.000 0.000 0.000 1.000 -1.000 0.000]]


In [ ]:
x1 = 0
x2 = 0
x3 = 0
i = 0

respostas1 = [0]

error = 5

while error > 0.0001:
    
    i += 1
    
    x1 = (m[0][3] - m[0][1]*x2 - m[0][2]*x3) / m[0][0]
    
    respostas1.append(x1)
    
    x2 = (m[1][3] - m[1][0]*x1 - m[1][2]*x3) / m[1][1]
    
    x3 = (m[2][3] - m[2][0]*x1 - m[2][1]*x2) / m[2][2]
    
    error = math.fabs(100*(x1 - respostas1[i-1])/x1)


print(x1)
print(x2)
print(x3)
print(i)
print(error)

### Exercício 12.25
utilizar eliminação de Gauss com pivotamento.

In [ ]:
matrix = np.array([[1, -1,-1, 0, 0, 0, 0],
    
                   [10,-5,0,-25,0,0,200],
                   
                   [0, 5,-20, 0,-5,-2,0],
    
                   [0,-1, 0, 1, -1, 0, 0],
                   
                   [0, 0, 1, 0, 0,-1, 0],
                   
                   [0, 0, 0, 0, 1,-1, 0]])

matrix = matrix.astype('float64')
print(matrix)

### Exercício 12.27

### Exercício 12.28