## APS 2 - Sistemas de equações (matrizes).

Considerar epsilon_s = 0,0001%.

Explicar como funcionam os comandos de inversão de matriz e multiplicação de matrizes usados pela linguagem de programação Python.

In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

%matplotlib inline

### Exercício 12.23 

<img src="scan2.JPG">

In [2]:
matrix = np.array([    [1,-1,-1,0],
                       [-35,0,-5,200],
                       [0,-27,5,0]
                       ])

matrix = matrix.astype('float64')

### Utilizando a eliminação de Gauss ingênua:

In [3]:
temp = matrix[1][0]/matrix[0][0]
for i in range(4): 
    matrix[1][i] -= temp*matrix[0][i]

In [4]:
temp = matrix[2][1]/matrix[1][1]
for i in range(4): 
    matrix[2][i] -= temp*matrix[1][i]

In [5]:
print(matrix)

[[1.000 -1.000 -1.000 0.000]
 [0.000 -35.000 -40.000 200.000]
 [0.000 0.000 35.857 -154.286]]


### i3:

In [6]:
i3 = -154.286/35.857
print(i3)

-4.302813955434085


### i2:

In [7]:
i2 = (40*i3+200)/-35
print(i2)

-0.7967840509324738


### i1:

In [8]:
i1 = i2+i3
print(i1)

-5.099598006366559


### O sinal negativo da corrente indica que ela tem sinal contrário ao que está no desenho acima.

### Exercício 12.25
utilizar eliminação de Gauss com pivotamento.

<img src="exercicio25.JPG">

### Matriz obtida a partir das leis de Kirchoff aplicadas ao circuito elétrico:

In [38]:
matrix = np.array([  
    
    [-75,-25, 0,  0,-20, 0,-70],    
    [0  ,-25,-5,  0,  0, 0,  0],     
    [0  ,  0,-5,-10, 25, 0,  0],     
    [1  , -1, 0,  0,  0,-1,  0],    
    [1  ,  0, 0, -1, -1, 0,  0],    
    [0  ,  1, -1, 0, -1, 0,  0]    
                       ])

matrix = matrix.astype('float64')

### Matriz pivotada manualmente:

In [39]:
matrix = np.array([  
    
    [-75,-25, 0,  0,-20, 0,-70], 
    [0  ,-25,-5,  0,  0, 0,  0],
    [0  ,  0,-5,-10, 25, 0,  0], 
    [1  ,  0, 0, -1, -1, 0,  0], 
    [0  ,  1, -1, 0, -1, 0,  0],
    [1  , -1, 0,  0,  0,-1,  0]       
                       ])

matrix = matrix.astype('float64')

Primeiro coeficiente:

In [40]:
temp = matrix[3][0]/matrix[0][0]
for i in range(7): 
    matrix[3][i] -= temp*matrix[0][i]

temp = matrix[5][0]/matrix[0][0]
for i in range(7): 
    matrix[5][i] -= temp*matrix[0][i]

In [41]:
print(matrix)

[[-75.000 -25.000 0.000 0.000 -20.000 0.000 -70.000]
 [0.000 -25.000 -5.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 -5.000 -10.000 25.000 0.000 0.000]
 [0.000 -0.333 0.000 -1.000 -1.267 0.000 -0.933]
 [0.000 1.000 -1.000 0.000 -1.000 0.000 0.000]
 [0.000 -1.333 0.000 0.000 -0.267 -1.000 -0.933]]


Segundo coeficiente:

In [42]:
temp = matrix[3][1]/matrix[1][1]
for i in range(7): 
    matrix[3][i] -= temp*matrix[1][i]

temp = matrix[4][1]/matrix[1][1]
for i in range(7): 
    matrix[4][i] -= temp*matrix[1][i]

temp = matrix[5][1]/matrix[1][1]
for i in range(7): 
    matrix[5][i] -= temp*matrix[1][i]

In [43]:
print(matrix)

[[-75.000 -25.000 0.000 0.000 -20.000 0.000 -70.000]
 [0.000 -25.000 -5.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 -5.000 -10.000 25.000 0.000 0.000]
 [0.000 0.000 0.067 -1.000 -1.267 0.000 -0.933]
 [0.000 0.000 -1.200 0.000 -1.000 0.000 0.000]
 [0.000 0.000 0.267 0.000 -0.267 -1.000 -0.933]]


Terceiro coeficiente:

In [44]:
temp = matrix[3][2]/matrix[2][2]
for i in range(6): 
    matrix[3][i] -= temp*matrix[2][i]

temp = matrix[4][2]/matrix[2][2]
for i in range(6): 
    matrix[4][i] -= temp*matrix[2][i]

temp = matrix[5][2]/matrix[2][2]
for i in range(6): 
    matrix[5][i] -= temp*matrix[2][i]

In [45]:
print(matrix)

[[-75.000 -25.000 0.000 0.000 -20.000 0.000 -70.000]
 [0.000 -25.000 -5.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 -5.000 -10.000 25.000 0.000 0.000]
 [0.000 0.000 0.000 -1.133 -0.933 0.000 -0.933]
 [0.000 0.000 0.000 2.400 -7.000 0.000 0.000]
 [0.000 0.000 0.000 -0.533 1.067 -1.000 -0.933]]


Quarto coeficiente:

In [46]:
temp = matrix[4][3]/matrix[3][3]
for i in range(7): 
    matrix[4][i] -= temp*matrix[3][i]
    
temp = matrix[5][3]/matrix[3][3]
for i in range(7): 
    matrix[5][i] -= temp*matrix[3][i]

In [47]:
print(matrix)

[[-75.000 -25.000 0.000 0.000 -20.000 0.000 -70.000]
 [0.000 -25.000 -5.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 -5.000 -10.000 25.000 0.000 0.000]
 [0.000 0.000 0.000 -1.133 -0.933 0.000 -0.933]
 [0.000 0.000 0.000 0.000 -8.976 0.000 -1.976]
 [0.000 0.000 0.000 0.000 1.506 -1.000 -0.494]]


Quinto coeficiente:

In [48]:
temp = matrix[5][4]/matrix[4][4]
for i in range(7): 
    matrix[5][i] -= temp*matrix[4][i]

In [49]:
print(matrix)

[[-75.000 -25.000 0.000 0.000 -20.000 0.000 -70.000]
 [0.000 -25.000 -5.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 -5.000 -10.000 25.000 0.000 0.000]
 [0.000 0.000 0.000 -1.133 -0.933 0.000 -0.933]
 [0.000 0.000 0.000 0.000 -8.976 0.000 -1.976]
 [0.000 0.000 0.000 0.000 0.000 -1.000 -0.826]]


### i6:

In [50]:
i6 = -0.826/-1
print(i6)

0.826


### i5:

In [51]:
i5 = -1.976/-8.976
print(i5)

0.22014260249554365


### i4:

In [54]:
i4 = (-0.933 + 0.933*i5)/-1.133
print(i4)

0.6421950148911366


### i3:

In [55]:
i3 = (-25*i5 + 10*i4)/-5
print(i3)

-0.1836770173045549


### i2:

In [56]:
i2 = 5*i3/-25
print(i2)

0.03673540346091098


### i1:

In [57]:
i1 = (-70+20*i5+25*i2)/-75
print(i1)

0.8623835048475513


### Exercício 12.27

<img src="exercicio27.JPG">

### Utilizando eliminação de Gauss com pivotamento (pivotamento executado manualmente), vem:

O pivotamento cumpre o propósito de evitar a divisão por zero na eliminação de Gauss, e consiste em reordenar as linhas de forma que o elemento pivô (geralmente o da diagonal principal), não seja zero.

### Matriz obtida a partir das leis de Kirchoff aplicadas ao circuito elétrico:

In [9]:
matrix = np.array([  
    
    
    [0 ,0  ,1  ,1  ,-1,  0],
    [-1,0  ,1  ,0  ,1 ,  0],  
    [-1,1  ,1  ,0  ,0 ,  0], 
    [-5,0  ,-15,0  ,0 ,-80], 
    [0 ,0  ,-20,25 ,0 , 50]              
                       ])

matrix = matrix.astype('float64')

### Matriz pivotada:

In [10]:
matrix = np.array([  
    
    [-5,0  ,-15,0  ,0 ,-80],
    [-1,1  ,1  ,0  ,0 ,  0],
    [-1,0  ,1  ,0  ,1 ,  0], 
    [0 ,0  ,1  ,1  ,-1,  0],
    [0 ,0  ,-20,25 ,0 , 50]              
                       ])

matrix = matrix.astype('float64')

Primeiro coeficiente:

In [11]:
temp = matrix[1][0]/matrix[0][0]
for i in range(6): 
    matrix[1][i] -= temp*matrix[0][i]

temp = matrix[2][0]/matrix[0][0]
for i in range(6): 
    matrix[2][i] -= temp*matrix[0][i]

In [12]:
print(matrix)

[[-5.000 0.000 -15.000 0.000 0.000 -80.000]
 [0.000 1.000 4.000 0.000 0.000 16.000]
 [0.000 0.000 4.000 0.000 1.000 16.000]
 [0.000 0.000 1.000 1.000 -1.000 0.000]
 [0.000 0.000 -20.000 25.000 0.000 50.000]]


Terceiro coeficiente:

In [13]:
temp = matrix[3][2]/matrix[2][2]
for i in range(6): 
    matrix[3][i] -= temp*matrix[2][i]

temp = matrix[4][2]/matrix[2][2]
for i in range(6): 
    matrix[4][i] -= temp*matrix[2][i]

In [14]:
print(matrix)

[[-5.000 0.000 -15.000 0.000 0.000 -80.000]
 [0.000 1.000 4.000 0.000 0.000 16.000]
 [0.000 0.000 4.000 0.000 1.000 16.000]
 [0.000 0.000 0.000 1.000 -1.250 -4.000]
 [0.000 0.000 0.000 25.000 5.000 130.000]]


Quarto coeficiente:

In [15]:
temp = matrix[4][3]/matrix[3][3]
for i in range(6): 
    matrix[4][i] -= temp*matrix[3][i]

In [16]:
print(matrix)

[[-5.000 0.000 -15.000 0.000 0.000 -80.000]
 [0.000 1.000 4.000 0.000 0.000 16.000]
 [0.000 0.000 4.000 0.000 1.000 16.000]
 [0.000 0.000 0.000 1.000 -1.250 -4.000]
 [0.000 0.000 0.000 0.000 36.250 230.000]]


### Substituição regressiva:

### i5:

In [17]:
i5 = 230.000/36.250
print(i5)

6.344827586206897


### i4:

In [18]:
i4 = -4 + 1.25*i5
print(i4)

3.931034482758621


### i3:

In [19]:
i3 = (16) -i5 /4
print(i3)

14.413793103448276


### i2:

In [20]:
i2 = 16 - 4*i3
print(i2)

-41.6551724137931


### i1:

In [21]:
i1 = (-80 + 15*i3) / 5
print(i1)

27.241379310344826


### Exercício 12.28

<img src="exercicio28.JPG">

### Matriz obtida a partir das leis de Kirchoff aplicadas ao circuito elétrico:

In [22]:
matrix = np.array([  
    
    [1,-1 ,-1, 0, 0, 0,  0],    
    [0, 1 , 0, 0, 1,-1,  0],     
    [0, 0 ,-4,-2, 0, 0,-20],     
    [0 ,-6, 4, 0, 8, 0,  0],    
    [0 ,0 ,-1, 1, 1, 0,  0],    
    [0 ,0 , 0,-2, 8, 5,  0]    
                       ])

matrix = matrix.astype('float64')

### Matriz pivotada manualmente:

In [23]:
matrix = np.array([  
    
    [1,-1 ,-1, 0, 0, 0,  0],    
    [0, 1 , 0, 0, 1,-1,  0],     
    [0, 0 ,-4,-2, 0, 0,-20], 
    [0 ,0 ,-1, 1, 1, 0,  0], 
    [0 ,-6, 4, 0, 8, 0,  0],    
    [0 ,0 , 0,-2, 8, 5,  0]    
                       ])

matrix = matrix.astype('float64')

Segundo coeficiente:

In [24]:
temp = matrix[4][1]/matrix[1][1]
for i in range(7): 
    matrix[4][i] -= temp*matrix[1][i]

In [25]:
print(matrix)

[[1.000 -1.000 -1.000 0.000 0.000 0.000 0.000]
 [0.000 1.000 0.000 0.000 1.000 -1.000 0.000]
 [0.000 0.000 -4.000 -2.000 0.000 0.000 -20.000]
 [0.000 0.000 -1.000 1.000 1.000 0.000 0.000]
 [0.000 0.000 4.000 0.000 14.000 -6.000 0.000]
 [0.000 0.000 0.000 -2.000 8.000 5.000 0.000]]


Terceiro coeficiente:

In [26]:
temp = matrix[3][2]/matrix[2][2]
for i in range(7): 
    matrix[3][i] -= temp*matrix[2][i]

temp = matrix[4][2]/matrix[2][2]
for i in range(7): 
    matrix[4][i] -= temp*matrix[2][i]

In [27]:
print(matrix)

[[1.000 -1.000 -1.000 0.000 0.000 0.000 0.000]
 [0.000 1.000 0.000 0.000 1.000 -1.000 0.000]
 [0.000 0.000 -4.000 -2.000 0.000 0.000 -20.000]
 [0.000 0.000 0.000 1.500 1.000 0.000 5.000]
 [0.000 0.000 0.000 -2.000 14.000 -6.000 -20.000]
 [0.000 0.000 0.000 -2.000 8.000 5.000 0.000]]


Quarto coeficiente:

In [28]:
temp = matrix[4][3]/matrix[3][3]
for i in range(7): 
    matrix[4][i] -= temp*matrix[3][i]
    
temp = matrix[5][3]/matrix[3][3]
for i in range(7): 
    matrix[5][i] -= temp*matrix[3][i]

In [29]:
print(matrix)

[[1.000 -1.000 -1.000 0.000 0.000 0.000 0.000]
 [0.000 1.000 0.000 0.000 1.000 -1.000 0.000]
 [0.000 0.000 -4.000 -2.000 0.000 0.000 -20.000]
 [0.000 0.000 0.000 1.500 1.000 0.000 5.000]
 [0.000 0.000 0.000 0.000 15.333 -6.000 -13.333]
 [0.000 0.000 0.000 0.000 9.333 5.000 6.667]]


Quinto coeficiente:

In [30]:
temp = matrix[5][4]/matrix[4][4]
for i in range(7): 
    matrix[5][i] -= temp*matrix[4][i]

In [31]:
print(matrix)

[[1.000 -1.000 -1.000 0.000 0.000 0.000 0.000]
 [0.000 1.000 0.000 0.000 1.000 -1.000 0.000]
 [0.000 0.000 -4.000 -2.000 0.000 0.000 -20.000]
 [0.000 0.000 0.000 1.500 1.000 0.000 5.000]
 [0.000 0.000 0.000 0.000 15.333 -6.000 -13.333]
 [0.000 0.000 0.000 0.000 0.000 8.652 14.783]]


### i6:

In [32]:
i6 = 14.783/8.652
print(i6)

1.7086222838650025


### i5:

In [33]:
i5 = (6.000*i6 - 13.333)/15.333
print(i5)

-0.20095651841192105


### i4:

In [34]:
i4 = (5-i5)/1.5
print(i4)

3.4673043456079475


### i3:

In [35]:
i3 = (-20 + 2*i4)/-4
print(i3)

3.266347827196026


### i2:

In [36]:
i2 = i6-i5
print(i2)

1.9095788022769236


### i1:

In [37]:
i1 = i2+i3
print(i1)

5.17592662947295
