## APS 2 - Sistemas de equações (matrizes).

Considerar epsilon_s = 0,0001%.

Explicar como funcionam os comandos de inversão de matriz e multiplicação de matrizes usados pela linguagem de programação Python.

In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

%matplotlib inline

### Exercício 12.23 

In [57]:
matrix = np.array([    [1,-1,-1,0],
                       [-35,0,-5,200],
                       [0,-27,5,0]
                       ])

matrix = matrix.astype('float64')

### Utilizando a eliminação de Gauss ingênua:

In [58]:
temp = matrix[1][0]/matrix[0][0]
for i in range(4): 
    matrix[1][i] -= temp*matrix[0][i]

In [60]:
temp = matrix[2][1]/matrix[1][1]
for i in range(4): 
    matrix[2][i] -= temp*matrix[1][i]

In [61]:
print(matrix)

[[1.000 -1.000 -1.000 0.000]
 [0.000 -35.000 -40.000 200.000]
 [0.000 0.000 35.857 -154.286]]


### Exercício 12.25
utilizar eliminação de Gauss com pivotamento.

### Exercício 12.27

### Utilizando eliminação de Gauss com pivotamento (mesmo código usado acima, com pivotamento executado manualmente), vem:

In [40]:
matrix = np.array([   
    [1,-1,0,0,0,1,0],
    [0,1,-1,1,0,0,0],
    [-20,-10,-5,0,0,0,30],
    [0,0,1,-1,-1,0,0],
    [1,0,0,0,-1,1,0],
    [-20,0,0,0,0,25,-50]                   
                       ])

matrix = matrix.astype('float64')

Primeiro coeficiente:

In [26]:
temp = matrix[2][0]/matrix[0][0]
for i in range(7): 
    matrix[2][i] -= temp*matrix[0][i]

In [27]:
print(matrix)

[[1.000 -1.000 0.000 0.000 0.000 1.000 0.000]
 [0.000 1.000 -1.000 1.000 0.000 0.000 0.000]
 [0.000 -30.000 -5.000 0.000 0.000 20.000 30.000]
 [0.000 0.000 1.000 -1.000 -1.000 0.000 0.000]
 [0.000 1.000 0.000 0.000 -1.000 0.000 0.000]
 [0.000 -20.000 0.000 0.000 0.000 45.000 -50.000]]


Segundo coeficiente:

In [28]:
temp = matrix[2][1]/matrix[1][1]
for i in range(7): 
    matrix[2][i] -= temp*matrix[1][i]

In [ ]:
temp = matrix[2][0]/matrix[0][0]
for i in range(7): 
    matrix[2][i] -= temp*matrix[0][i]

In [ ]:
temp = matrix[2][0]/matrix[0][0]
for i in range(7): 
    matrix[2][i] -= temp*matrix[0][i]

In [29]:
print(matrix)

[[1.000 -1.000 0.000 0.000 0.000 1.000 0.000]
 [0.000 1.000 -1.000 1.000 0.000 0.000 0.000]
 [0.000 0.000 -35.000 30.000 0.000 20.000 30.000]
 [0.000 0.000 1.000 -1.000 -1.000 0.000 0.000]
 [0.000 1.000 0.000 0.000 -1.000 0.000 0.000]
 [0.000 -20.000 0.000 0.000 0.000 45.000 -50.000]]


### Exercício 12.28

In [ ]:
matrix = np.array([   
    [1,0,0,0,1,-1,0],
    [1,-1,0,1,0,0,0],
    [0,0,1,-1,1,0,0],
    [0,-1,1,0,0,1,0],
    [0,0,2,0,-4,0,-20],
    [-6,0,0,8,4,0,0]                   
                       ])

matrix = matrix.astype('float64')