## APS 2 - Sistemas de equações (matrizes).

Considerar epsilon_s = 0,0001%.

Explicar como funcionam os comandos de inversão de matriz e multiplicação de matrizes usados pela linguagem de programação Python.

In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

%matplotlib inline

### Exercício 12.23 

In [ ]:
matrix = np.array([    [1,-1,-1,0],
                       [-35,0,-5,200],
                       [0,-27,5,0]
                       ])

matrix = matrix.astype('float64')

### Utilizando a eliminação de Gauss ingênua:

In [ ]:
for i in range(1,3):
    for j in range(4):
        if i > j:
            if matrix[i][j] != 0:
                temp = matrix[i][j]/matrix[j][j]
                for k in range(4):
                    matrix[i][k] -= temp*matrix[j][k]
print(matrix)    

In [ ]:
i3 = -154.286/35.857
print(i3)

In [ ]:
i2 = (200 + 40*i3)/-35
print(i2)

In [ ]:
i1 = i3 + i2 
print(i1)

### Exercício 12.25
utilizar eliminação de Gauss com pivotamento.

### Exercício 12.27

### Utilizando eliminação de Gauss com pivotamento (mesmo código usado acima), vem:

In [11]:
matrix = np.array([   
    [1,-1,0,0,0,1,0],
    [0,1,-1,1,0,0,0],
    [-20,-10,-5,0,0,0,30],
    [0,0,1,-1,-1,0,0],
    [1,0,0,0,-1,1,0],
    [-20,0,0,0,0,25,-50]                   
                       ])

matrix = matrix.astype('float64')

In [10]:
for i in range(1,6):
    for j in range(7):
        if i > j:
            if matrix[i][j] != 0:
                temp = matrix[i][j]/matrix[j][j]
                for k in range(7):
                    matrix[i][k] -= temp*matrix[j][k]
print(matrix)   

[[1.000 -1.000 0.000 0.000 0.000 1.000 0.000]
 [0.000 1.000 -1.000 1.000 0.000 0.000 0.000]
 [0.000 0.000 -35.000 30.000 0.000 20.000 30.000]
 [0.000 0.000 0.000 -0.143 -1.000 0.571 0.857]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.000]
 [nan nan nan nan nan nan nan]]


C:\Users\User\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  """
C:\Users\User\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in double_scalars
  import sys


### Como o código não rodou, executando o pivotamento manualmente para cada coeficiente, vem:

Primeiro coeficiente:

In [12]:
temp = matrix[2][0]/matrix[0][0]
for i in range(7): 
    matrix[2][i] -= temp*matrix[0][i]

In [13]:
temp = matrix[4][0]/matrix[0][0]
for i in range(7): 
    matrix[4][i] -= temp*matrix[0][i]

In [14]:
temp = matrix[5][0]/matrix[0][0]
for i in range(7): 
    matrix[5][i] -= temp*matrix[0][i]

In [ ]:
matrix = np.array([   
    [1,-1,0,0,0,1,0],
    [0,1,-1,1,0,0,0],
    [-20,-10,-5,0,0,0,30],
    [0,0,1,-1,-1,0,0],
    [1,0,0,0,-1,1,0],
    [-20,0,0,0,0,25,-50]                   
                       ])

matrix = matrix.astype('float64')

Segundo coeficiente:

In [16]:
temp = matrix[1][1]/matrix[0][1]
for i in range(7): 
    matrix[1][i] -= temp*matrix[1][i]

In [ ]:
temp = matrix[2][0]/matrix[0][0]
for i in range(7): 
    matrix[2][i] -= temp*matrix[0][i]

In [ ]:
temp = matrix[2][0]/matrix[0][0]
for i in range(7): 
    matrix[2][i] -= temp*matrix[0][i]

In [17]:
print(matrix)

[[1.000 -1.000 0.000 0.000 0.000 1.000 0.000]
 [0.000 2.000 -2.000 2.000 0.000 0.000 0.000]
 [0.000 -30.000 -5.000 0.000 0.000 20.000 30.000]
 [0.000 0.000 1.000 -1.000 -1.000 0.000 0.000]
 [0.000 1.000 0.000 0.000 -1.000 0.000 0.000]
 [0.000 -20.000 0.000 0.000 0.000 45.000 -50.000]]


### Exercício 12.28

In [ ]:
matrix = np.array([   
    [1,0,0,0,1,-1,0],
    
    [1,-1,0,1,0,0,0],
    
    [0,0,1,-1,1,0,0],
    
    [0,-1,1,0,0,1,0],
    
    [0,0,2,0,-4,0,-20],
    
    [-6,0,0,8,4,0,0]                   
                       ])

matrix = matrix.astype('float64')