### Exercício 9.13
O sistema é bem ou mal condicionado?

In [1]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

In [2]:
matrix = np.array([[1,1,-1,-3],[6,2,2,2],[-3,4,1,1]])
matrix = matrix.astype('float64')
print(matrix)

[[1.000 1.000 -1.000 -3.000]
 [6.000 2.000 2.000 2.000]
 [-3.000 4.000 1.000 1.000]]


## Eliminação de Gauss ingênuo

### Eliminação progressiva:

In [3]:
for i in range(1,3):
    for j in range(4):
        if i > j:
            if matrix[i][j] != 0:
                temp = matrix[i][j]/matrix[j][j]
                for k in range(4):
                    matrix[i][k] -= temp*matrix[j][k]
print(matrix)    

[[1.000 1.000 -1.000 -3.000]
 [0.000 -4.000 8.000 20.000]
 [0.000 0.000 12.000 27.000]]


## Sendo assim, as raízes são iguais a:

### Iniciando pela última linha 3:

In [4]:
x3 = 27/12
print(x3)

2.25


### Linha 2:

In [5]:
x2 = (-8*x3 + 20)/-4
print(x2)

-0.5


### Linha 1:

In [6]:
x1 = -3 + x3 - x2
print(x1)

-0.25


## Eliminação de Gauss com pivotamento parcial (pivotamento de linhas)

### Fazendo o pivotamento manualmente:

In [22]:
matrix = np.array([[1,1,-1,-3],[6,2,2,2],[-3,4,1,1]])
matrix = matrix.astype('float64')
print(matrix)

[[1.000 1.000 -1.000 -3.000]
 [6.000 2.000 2.000 2.000]
 [-3.000 4.000 1.000 1.000]]


In [7]:
matrix = np.array([[6,2,2,2],[-3,4,1,1],[1,1,-1,-3]])
matrix = matrix.astype('float64')
print(matrix)

[[6.000 2.000 2.000 2.000]
 [-3.000 4.000 1.000 1.000]
 [1.000 1.000 -1.000 -3.000]]


In [8]:
for i in range(1,3):
    for j in range(4):
        if i > j:
            if matrix[i][j] != 0:
                temp = matrix[i][j]/matrix[j][j]
                for k in range(4):
                    matrix[i][k] -= temp*matrix[j][k]

print(matrix)          

[[6.000 2.000 2.000 2.000]
 [0.000 5.000 2.000 2.000]
 [0.000 0.000 -1.600 -3.600]]


## Sendo assim, as raízes são iguais a:

In [9]:
x3 = -3.6/-1.6
print(x3)

x2 = (-2*x3 + 2)/5
print(x2)

x1 = (2 - 2*x3 - 2*x2)/6
print(x1)

2.25
-0.5
-0.25


## Gauss-Jordan sem pivotamento

In [10]:
matrix = np.array([[1,1,-1,-3],[6,2,2,2],[-3,4,1,1]])
matrix = matrix.astype('float64')
print(matrix)

[[1.000 1.000 -1.000 -3.000]
 [6.000 2.000 2.000 2.000]
 [-3.000 4.000 1.000 1.000]]


In [11]:
for i in range(1,3):
    for j in range(4):
        if i > j:
            if matrix[i][j] != 0:
                temp = matrix[i][j]/matrix[j][j]
                for k in range(4):
                    matrix[i][k] -= temp*matrix[j][k]   
    
         
for i in range(3):
    for j in range(1,3):
        if i < j:
            if matrix[i][j] != 0:
                temp = matrix[i][j]/matrix[j][j]
                for k in range(4):
                    matrix[i][k] -= temp*matrix[j][k]   

                
"""               
for i in range(3):
    for j in range(4):
        for k in range(4):
            matrix[i][k] /= matrix[i][i] 
""" 
            

                                          
print(matrix)  

[[1.000 0.000 0.000 -0.250]
 [0.000 -4.000 0.000 2.000]
 [0.000 0.000 12.000 27.000]]


### Dividindo-se cada membro pelo termo da identidade, tem-se a seguinte matriz:

In [12]:
matrix = np.array([[1,0,0,-0.25],[0,1,0,-0.5],[0,0,1,2.25]])
matrix = matrix.astype('float64')
print(matrix)

[[1.000 0.000 0.000 -0.250]
 [0.000 1.000 0.000 -0.500]
 [0.000 0.000 1.000 2.250]]


## Sendo assim, as raízes são iguais a:

In [13]:
x3 = 27/12
print(x1)

-0.25


In [14]:
x2 = 2/-4
print(x2)

-0.5


In [15]:
x3 = -0.25/1
print(x3)

-0.25


## O determinante deste sistema é igual a -48 antes da mudança de escala, e após, é -2 o que é distante de zero. portanto o sistema é bem condicionado.

In [23]:
matrix = np.array([[1,-45,-20,0,0,0,0],
                   [0,1,0.25,0.05,0,0,475],
                   [0,1,2,0,0,1,550],
                   [0,0.04,0.12,0,1,0,40],
                   ])
matrix = matrix.astype('float64')
print(matrix)

[[1.000 -45.000 -20.000 0.000 0.000 0.000 0.000]
 [0.000 1.000 0.250 0.050 0.000 0.000 475.000]
 [0.000 1.000 2.000 0.000 0.000 1.000 550.000]
 [0.000 0.040 0.120 0.000 1.000 0.000 40.000]]


In [24]:
for i in range(1,4):
    for j in range(7):
        if i > j:
            if matrix[i][j] != 0:
                temp = matrix[i][j]/matrix[j][j]
                for k in range(7):
                    matrix[i][k] -= temp*matrix[j][k]

print(matrix)     

[[1.000 -45.000 -20.000 0.000 0.000 0.000 0.000]
 [0.000 1.000 0.250 0.050 0.000 0.000 475.000]
 [0.000 0.000 1.750 -0.050 0.000 1.000 75.000]
 [0.000 0.000 -0.000 0.001 1.000 -0.063 16.286]]
