# Exercício da aula 10.

Exercício 10.8

In [1]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{0:0.9f}".format(x)})

In [2]:
matrix = np.array([[15,-3,-1],[-3,18,-6],[-4,-1,12]])
matrix = matrix.astype('float64')
print(matrix)

[[15.000000000 -3.000000000 -1.000000000]
 [-3.000000000 18.000000000 -6.000000000]
 [-4.000000000 -1.000000000 12.000000000]]


# a) Determinação da matriz inversa. 

Eliminação progressiva:

No loop abaixo foram "printados" os fatores utilizados na eliminação, que serão empregados na montagem da matriz L.

In [3]:
U = np.array([[15,-3,-1],[-3,18,-6],[-4,-1,12]])
U = U.astype('float64')

In [4]:
for i in range(1,3):
    for j in range(3):
        if i > j:
            if U[i][j] != 0:
                temp = U[i][j]/U[j][j]
                print(temp)
                for k in range(3):
                    U[i][k] -= temp*U[j][k]
print(U)    

-0.2
-0.26666666666666666
-0.10344827586206898
[[15.000000000 -3.000000000 -1.000000000]
 [0.000000000 17.400000000 -6.200000000]
 [0.000000000 0.000000000 11.091954023]]


Assim, é possível montar a matriz L:

In [5]:
L = np.array([[1,          0,0],
              [-0.2,       1,0],
              [-0.266666666666,-0.10344827,1]])
L = L.astype('float64')
print(L)

[[1.000000000 0.000000000 0.000000000]
 [-0.200000000 1.000000000 0.000000000]
 [-0.266666667 -0.103448270 1.000000000]]


In [6]:
A = np.matmul(L, U)
print(A)

[[15.000000000 -3.000000000 -1.000000000]
 [-3.000000000 18.000000000 -6.000000000]
 [-4.000000000 -0.999999898 11.999999964]]


# Cálculo da matriz D, primeira coluna:

### Primeira coluna:

In [7]:
d1 = 1
print(d1)
d2 = d1*0.2
print(d2)
d3 = 0.2666666*d1 + 0.10344827*d2
print(d3)

1
0.2
0.287356254


# Cálculo da matriz X, primeira coluna:

In [8]:
x3 = d3/11.0919540
print(x3)

x2 = (d2 + 6.2*x3)/17.4
print(x2)

x1 = (3*x2+d3+x3)/15
print(x1)

0.025906729688925864
0.020725386440881635
0.025029276200771385


# Cálculo da matriz D, segunda coluna:

In [9]:
d1 = 0
print(d1)
d2 = 1 + 0.2*d1
print(d2)
d3 = 0.2666666*d1 + 0.10344827*d2
print(d3)

0
1.0
0.10344827


# Cálculo da matriz X, segunda coluna:

In [10]:
x3 = d3/11.0919540
print(x3)

x2 = (d2 + 6.2*x3)/17.4
print(x2)

x1 = (3*x2+d3+x3)/15
print(x1)

0.00932642436129829
0.06079447304827871
0.019677207567075628


# Cálculo da matriz D, terceira coluna:

In [11]:
d1 = 0
print(d1)
d2 = d1*0.2
print(d2)
d3 = 0.2666666*d1 + 0.10344827*d2 +1
print(d3)

0
0.0
1.0


# Cálculo da matriz X, terceira coluna:

In [12]:
x3 = d3/11.0919540
print(x3)

x2 = (d2 + 6.2*x3)/17.4
print(x2)

x1 = (3*x2+d3+x3)/15
print(x1)

0.09015544060135842
0.03212435239818519
0.07910189985306094


In [13]:
INV = np.array([[0.025906729688925864, 0.00932642436129829, 0.09015544060135842],
                [0.020725386440881635, 0.06079447304827871, 0.03212435239818519],
                [0.025029276200771385, 0.019677207567075628, 0.07910189985306094]])
INV = INV.astype('float64')
print(INV)

[[0.025906730 0.009326424 0.090155441]
 [0.020725386 0.060794473 0.032124352]
 [0.025029276 0.019677208 0.079101900]]


In [14]:
identidade = np.matmul(INV, A)
print(identidade)

[[-0.000000090 0.000000018 1.000000008]
 [-0.000000032 1.000000006 0.000000003]
 [-0.000000079 0.200000016 0.806130274]]


# b) Utilizar a inversa para obter a solução.

# c) Determinar quanto aumentar a taxa de massa no reator 3 para induzir a um aumento DE 10 na concentração do reator 1. 

# d) Determinar de quanto diminuirá a concentração no reator 3 se a entrada de massa nos reatores 1 e 2 for reduzida DE 500 (no reator 1)
# e de 250 (no reator 2).